### PR TITLE
add option disable context menu

### LINKED ISSUE #43: feature: method to organize menu items
please consider adding a method whereby we can organize the menu items

### PR DESCRIPTION
**Pull request by Guest126**
maybe fix #43

### CODE REVIEW

**Comment by hnakamur** [comment]
Hi thanks for your pull request.
However I don't think this fixes #43 since I think it means the arranging orders of menu items or adding subset of menu items.
I wrote this extension for my own use and I don't need an option to disable context menu.

**Comment by Guest126** [comment]
Certainly #43 may be so.

However, my feature request is still here. It's a common request for any add-on. After Firefox shuts out context menu customization add-ons, context menus tend to be lengthy.

-[Why does Flagfox need to add itself to both the tab and main context menu? Why is there no option to disable this? - Flagfox](https://flagfox.net/viewtopic.php?f=3&t=766)
-[Make Context Menus Optional - Flagfox](https://flagfox.net/viewtopic.php?f=3&t=709)
-[Delete menu item - Flagfox](https://flagfox.net/viewtopic.php?f=3&t=746)

Of course, I could publish an add-on with this feature on AMO under the MIT License, but a similar add-on would confuse users. I believe this feature will benefit FormatLink users

If you still decide not to adopt this pull request, feel free to close this.

Thank you for your consideration!

**Comment by hnakamur** [comment]
Thanks for your explanation.
I'm convinced.
I am merging this and am releasing version 5.2.0.
Thanks for your contribution!

**Comment by Vingolf** [comment]
> I don't think this fixes #43 since I think it means the arranging orders of menu items

I aggree with your opinion, @hnakamur 
 #47 does not fix #43 completely.

Please consider adding options in the settings:

1. A method to reorder the entries in the settings e.g. by drag and drop or by up &#9650; and down  &#9660; buttons 
2. An option in the settings to choose active formats that appear in the context menu e.g. by by using checkmarks  ☑

**Comment by hnakamur** [comment]
Thanks for your comment.
I'd like to support those options, but I'm afraid I have no time for this right now.
Maybe someday I'll do it.

**Pull request merged**
